First pull request
sawmon71293/Hello-Microverse pull request #1
Opened 2023-01-10 10:37 UTC by sawmon71293

2023-01-10 12:09 UTC, franclobo requested changes
Hi @sawmon71293, 

# ♻️ REQUIRED CHANGES ♻️ 

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/211547689-e74685b9-59b3-4891-854e-99e447565f93.gif)

Good job so far!
You are doing it well for your first time 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- Good HTML file ✔️ 
- Correct Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 12:09 UTC, franclobo commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
- [ ] Please 🙏🏽 complete all the requirements before submitting your project, you have limited chances to approve it.
 - Kindly install the linter following these [instructions](https://github.com/microverseinc/linters-config/tree/master/html-css). All linters should be checking green.
![image](https://user-images.githubusercontent.com/58642949/211546481-85a74e62-810f-48f9-9a39-3509773ef50f.png)

  - The name of the feature branch should be descriptive e.g. `hello-world`, please 🙏🏽 fix it.
![image](https://user-images.githubusercontent.com/58642949/211546567-369947d4-75a1-42f7-aae7-3de9afc518a8.png)

  - Kindly follow the instruction of the [README template](https://github.com/microverseinc/readme-template) for a professional README file.
![image](https://user-images.githubusercontent.com/58642949/211546645-667d627a-9fde-49b5-a3f0-8220e4434f96.png)

  - Please 🙏🏽 edit your pull request description remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
![image](https://user-images.githubusercontent.com/58642949/211546721-4444db30-16d7-4ec0-9f61-5e40df2ffd05.png)

  - Kindly create all the files required to approve your project 👇🏽 

> Add a .gitignore file.
> Add node_modules to gitignore file.
> Add 3 files (each one in a separate commit):
> A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
> A .css file that includes one class with styles for your header (make it in your favorite color).
> A test.md file with the text "This file should be ignored by git".
> Make sure that the last file is actually ignored by git and is not present in your GitHub repository.

  - The commits should be meaningful, please 🙏🏽 describe the action that you did instead of the number of the commit 👇🏽 
![image](https://user-images.githubusercontent.com/58642949/211546404-b012f9b3-bd6f-47e2-93ab-c2b009d18311.png)

2023-01-10 18:02 UTC, sawmon71293 commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
@franclobo if I change the branch name , it will remove the pull request. How can I do about it?

2023-01-11 03:29 UTC, franclobo requested changes
Hi @sawmon71293, 

# ♻️ Required Changes ♻️

![soClose](https://user-images.githubusercontent.com/58642949/211710172-a2b9e0f5-8af4-4e1b-8bf3-29991742e605.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️
- Correct Github flow ✔️  


 ## Required Changes ♻️
_Check the comments under the review._

- I reviewed the PR in the `hello-world` branch and you didn't create a descriptive PR and didn't edit the current PR either. As I said before please 🙏🏽 edit the description in the PR to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

| Expected | Your PR |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/211709806-651e0bb5-794d-43cd-ab02-3f4880f5bb9b.png) | ![image](https://user-images.githubusercontent.com/58642949/211709845-d8dd08ba-5cad-4a1c-baf1-38f1532729e6.png) ![image](https://user-images.githubusercontent.com/58642949/211709894-a60d8c86-2105-4eb4-bd0d-a586b7858deb.png) |

May I help you? 👇🏽 

https://user-images.githubusercontent.com/58642949/211710933-1840980e-9a12-4bfe-b3ec-1ad03b88b0bc.mp4

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 03:29 UTC, franclobo commented on README.md
> +- Lincense
- **[OPTIONAL]** Instead of this list of Required sections, please 🙏🏽 add your own logo take in mind that all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo to have a professional README file.

2023-01-11 05:55 UTC, sawmon71293 commented on README.md
> +- Lincense
I will make sure to add next time. But how can I create a logo? Could you guide me?

2023-01-11 06:03 UTC, emmiiorji approved these changes
Hi @sawmon71293, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/211728784-ff9fbeae-357a-466b-ac1e-eaaa48d1b1d2.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Requested  change has been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 07:16 UTC, amejid approved these changes
Hi @sawmon71293, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 07:39 UTC, merged